# Generated by Django 5.0.6 on 2024-06-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='level',
            unique_together={('level', 'card')},
        ),
    ]
