# Generated by Django 5.0.6 on 2024-06-16 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_level_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('name', 'category')},
        ),
    ]
