# Generated by Django 5.0.6 on 2024-06-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_card_options_alter_card_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pkid',
            field=models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='pkid',
            field=models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='level',
            name='pkid',
            field=models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
