# Generated by Django 5.0.6 on 2024-06-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_card_pkid_alter_category_pkid_alter_level_pkid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pkid',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='pkid',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='level',
            name='pkid',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
