# Generated by Django 5.0.6 on 2024-06-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_card_pkid_alter_category_pkid_alter_level_pkid'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['name'], name='game_card_name_a356ae_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['category'], name='game_card_categor_8fe043_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='game_catego_name_76b326_idx'),
        ),
    ]
