# Generated by Django 5.0.6 on 2024-06-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_card_slug_alter_card_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, upload_to='card_images/'),
        ),
    ]
