# Generated by Django 5.0.6 on 2024-06-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_level_game_level_level_0eecce_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['slug'], name='game_card_slug_16d67d_idx'),
        ),
    ]
