# Generated by Django 5.0.6 on 2024-06-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_card_game_card_slug_16d67d_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=300, null=True),
        ),
    ]
