# Generated by Django 5.0.6 on 2024-07-08 21:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_alter_card_options'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiles',
            new_name='Profile',
        ),
        migrations.RenameModel(
            old_name='ProfileCards',
            new_name='ProfileCard',
        ),
        migrations.RenameModel(
            old_name='ProfileCardLevels',
            new_name='ProfileCardLevel',
        ),
        migrations.RenameIndex(
            model_name='profile',
            new_name='profiles_pr_pkid_51ae2c_idx',
            old_name='profiles_pr_pkid_7e229f_idx',
        ),
    ]
