# Generated by Django 5.0.6 on 2024-07-08 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_profiles_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecard',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_cards', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profilecardlevel',
            name='profile_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_card_levels', to='profiles.profilecard'),
        ),
    ]
