# Generated by Django 5.0.6 on 2024-07-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profilecard_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecard',
            name='max_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='ProfileCardLevel',
        ),
    ]
