# Generated by Django 5.0.6 on 2024-07-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_alter_card_options'),
        ('profiles', '0004_profilecard_max_level_delete_profilecardlevel'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profilecard',
            index=models.Index(fields=['profile'], name='profiles_pr_profile_233b85_idx'),
        ),
    ]
