# Generated by Django 5.0.6 on 2024-07-09 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profilecard_profiles_pr_profile_233b85_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_pr_pkid_51ae2c_idx',
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='profiles_pr_user_id_3364d1_idx'),
        ),
    ]
