# Generated by Django 5.0.6 on 2024-07-09 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_alter_card_options'),
        ('profiles', '0006_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilecard',
            old_name='max_level',
            new_name='level',
        ),
        migrations.AddField(
            model_name='profilecard',
            name='related_level',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='game.level'),
        ),
    ]
