# Generated by Django 5.0.6 on 2024-06-21 12:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0014_level_game_level_level_0eecce_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCombo',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('combo_date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('card_no_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cad1', to='game.card')),
                ('card_no_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cad2', to='game.card')),
                ('card_no_3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cad3', to='game.card')),
            ],
            options={
                'indexes': [models.Index(fields=['combo_date'], name='daily_daily_combo_d_7e0ac7_idx')],
            },
        ),
    ]
